//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int id { get; set; }
        public int isbn { get; set; }
        public string title { get; set; }
        public string author { get; set; }
        public string publish_year { get; set; }
        public int number_available { get; set; }
        public string publisher { get; set; }
        public string image { get; set; }
        public string summary { get; set; }
        public int category_fk { get; set; }
        public int language_fk { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Language Language { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
