//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LibraryManagementEntities : DbContext
    {
        public LibraryManagementEntities()
            : base("name=LibraryManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Reservation> Reservations { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<sp_book_save_Result> sp_book_save(Nullable<int> isbn, string title, string author, string publish_year, Nullable<int> number_available, string publisher, string image, string summary, string categoryName, string languageName)
        {
            var isbnParameter = isbn.HasValue ?
                new ObjectParameter("isbn", isbn) :
                new ObjectParameter("isbn", typeof(int));
    
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var authorParameter = author != null ?
                new ObjectParameter("author", author) :
                new ObjectParameter("author", typeof(string));
    
            var publish_yearParameter = publish_year != null ?
                new ObjectParameter("publish_year", publish_year) :
                new ObjectParameter("publish_year", typeof(string));
    
            var number_availableParameter = number_available.HasValue ?
                new ObjectParameter("number_available", number_available) :
                new ObjectParameter("number_available", typeof(int));
    
            var publisherParameter = publisher != null ?
                new ObjectParameter("publisher", publisher) :
                new ObjectParameter("publisher", typeof(string));
    
            var imageParameter = image != null ?
                new ObjectParameter("image", image) :
                new ObjectParameter("image", typeof(string));
    
            var summaryParameter = summary != null ?
                new ObjectParameter("summary", summary) :
                new ObjectParameter("summary", typeof(string));
    
            var categoryNameParameter = categoryName != null ?
                new ObjectParameter("categoryName", categoryName) :
                new ObjectParameter("categoryName", typeof(string));
    
            var languageNameParameter = languageName != null ?
                new ObjectParameter("languageName", languageName) :
                new ObjectParameter("languageName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_book_save_Result>("sp_book_save", isbnParameter, titleParameter, authorParameter, publish_yearParameter, number_availableParameter, publisherParameter, imageParameter, summaryParameter, categoryNameParameter, languageNameParameter);
        }
    
        public virtual ObjectResult<sp_user_login_Result> sp_user_login(string input_email, string input_password)
        {
            var input_emailParameter = input_email != null ?
                new ObjectParameter("input_email", input_email) :
                new ObjectParameter("input_email", typeof(string));
    
            var input_passwordParameter = input_password != null ?
                new ObjectParameter("input_password", input_password) :
                new ObjectParameter("input_password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_user_login_Result>("sp_user_login", input_emailParameter, input_passwordParameter);
        }
    
        public virtual ObjectResult<sp_user_save_Result> sp_user_save(string email, string password, string first_name, string last_name, Nullable<System.DateTime> date_of_birth, string gender, string phone_number, string address, Nullable<int> post_code, string city, string country, string membership_id, Nullable<bool> subscription, string interested_in, string roleName)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var first_nameParameter = first_name != null ?
                new ObjectParameter("first_name", first_name) :
                new ObjectParameter("first_name", typeof(string));
    
            var last_nameParameter = last_name != null ?
                new ObjectParameter("last_name", last_name) :
                new ObjectParameter("last_name", typeof(string));
    
            var date_of_birthParameter = date_of_birth.HasValue ?
                new ObjectParameter("date_of_birth", date_of_birth) :
                new ObjectParameter("date_of_birth", typeof(System.DateTime));
    
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            var phone_numberParameter = phone_number != null ?
                new ObjectParameter("phone_number", phone_number) :
                new ObjectParameter("phone_number", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var post_codeParameter = post_code.HasValue ?
                new ObjectParameter("post_code", post_code) :
                new ObjectParameter("post_code", typeof(int));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var countryParameter = country != null ?
                new ObjectParameter("country", country) :
                new ObjectParameter("country", typeof(string));
    
            var membership_idParameter = membership_id != null ?
                new ObjectParameter("membership_id", membership_id) :
                new ObjectParameter("membership_id", typeof(string));
    
            var subscriptionParameter = subscription.HasValue ?
                new ObjectParameter("subscription", subscription) :
                new ObjectParameter("subscription", typeof(bool));
    
            var interested_inParameter = interested_in != null ?
                new ObjectParameter("interested_in", interested_in) :
                new ObjectParameter("interested_in", typeof(string));
    
            var roleNameParameter = roleName != null ?
                new ObjectParameter("roleName", roleName) :
                new ObjectParameter("roleName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_user_save_Result>("sp_user_save", emailParameter, passwordParameter, first_nameParameter, last_nameParameter, date_of_birthParameter, genderParameter, phone_numberParameter, addressParameter, post_codeParameter, cityParameter, countryParameter, membership_idParameter, subscriptionParameter, interested_inParameter, roleNameParameter);
        }
    
        public virtual ObjectResult<sp_confirm_reservation_Result> sp_confirm_reservation(Nullable<System.DateTime> date_confirmed, string librarian_membership_id, string code)
        {
            var date_confirmedParameter = date_confirmed.HasValue ?
                new ObjectParameter("date_confirmed", date_confirmed) :
                new ObjectParameter("date_confirmed", typeof(System.DateTime));
    
            var librarian_membership_idParameter = librarian_membership_id != null ?
                new ObjectParameter("librarian_membership_id", librarian_membership_id) :
                new ObjectParameter("librarian_membership_id", typeof(string));
    
            var codeParameter = code != null ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_confirm_reservation_Result>("sp_confirm_reservation", date_confirmedParameter, librarian_membership_idParameter, codeParameter);
        }
    
        public virtual ObjectResult<sp_return_reservation_Result> sp_return_reservation(Nullable<System.DateTime> date_returned, string librarian_membership_id, string code)
        {
            var date_returnedParameter = date_returned.HasValue ?
                new ObjectParameter("date_returned", date_returned) :
                new ObjectParameter("date_returned", typeof(System.DateTime));
    
            var librarian_membership_idParameter = librarian_membership_id != null ?
                new ObjectParameter("librarian_membership_id", librarian_membership_id) :
                new ObjectParameter("librarian_membership_id", typeof(string));
    
            var codeParameter = code != null ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_return_reservation_Result>("sp_return_reservation", date_returnedParameter, librarian_membership_idParameter, codeParameter);
        }
    
        public virtual ObjectResult<sp_search_reservations_Result> sp_search_reservations(string membership_id, string email, string code, Nullable<System.DateTime> date_reserved_from, Nullable<System.DateTime> date_reserved_to, Nullable<bool> is_confirmed)
        {
            var membership_idParameter = membership_id != null ?
                new ObjectParameter("membership_id", membership_id) :
                new ObjectParameter("membership_id", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var codeParameter = code != null ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(string));
    
            var date_reserved_fromParameter = date_reserved_from.HasValue ?
                new ObjectParameter("date_reserved_from", date_reserved_from) :
                new ObjectParameter("date_reserved_from", typeof(System.DateTime));
    
            var date_reserved_toParameter = date_reserved_to.HasValue ?
                new ObjectParameter("date_reserved_to", date_reserved_to) :
                new ObjectParameter("date_reserved_to", typeof(System.DateTime));
    
            var is_confirmedParameter = is_confirmed.HasValue ?
                new ObjectParameter("is_confirmed", is_confirmed) :
                new ObjectParameter("is_confirmed", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_search_reservations_Result>("sp_search_reservations", membership_idParameter, emailParameter, codeParameter, date_reserved_fromParameter, date_reserved_toParameter, is_confirmedParameter);
        }
    
        public virtual ObjectResult<sp_book_edit_Result> sp_book_edit(Nullable<int> isbn, string title, string author, string publish_year, Nullable<int> number_available, string publisher, string image, string summary, string categoryName, string languageName)
        {
            var isbnParameter = isbn.HasValue ?
                new ObjectParameter("isbn", isbn) :
                new ObjectParameter("isbn", typeof(int));
    
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var authorParameter = author != null ?
                new ObjectParameter("author", author) :
                new ObjectParameter("author", typeof(string));
    
            var publish_yearParameter = publish_year != null ?
                new ObjectParameter("publish_year", publish_year) :
                new ObjectParameter("publish_year", typeof(string));
    
            var number_availableParameter = number_available.HasValue ?
                new ObjectParameter("number_available", number_available) :
                new ObjectParameter("number_available", typeof(int));
    
            var publisherParameter = publisher != null ?
                new ObjectParameter("publisher", publisher) :
                new ObjectParameter("publisher", typeof(string));
    
            var imageParameter = image != null ?
                new ObjectParameter("image", image) :
                new ObjectParameter("image", typeof(string));
    
            var summaryParameter = summary != null ?
                new ObjectParameter("summary", summary) :
                new ObjectParameter("summary", typeof(string));
    
            var categoryNameParameter = categoryName != null ?
                new ObjectParameter("categoryName", categoryName) :
                new ObjectParameter("categoryName", typeof(string));
    
            var languageNameParameter = languageName != null ?
                new ObjectParameter("languageName", languageName) :
                new ObjectParameter("languageName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_book_edit_Result>("sp_book_edit", isbnParameter, titleParameter, authorParameter, publish_yearParameter, number_availableParameter, publisherParameter, imageParameter, summaryParameter, categoryNameParameter, languageNameParameter);
        }
    
        public virtual ObjectResult<sp_search_books_Result> sp_search_books(string title, string author, string publish_year, string categoryName, string languageName, string roleName)
        {
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var authorParameter = author != null ?
                new ObjectParameter("author", author) :
                new ObjectParameter("author", typeof(string));
    
            var publish_yearParameter = publish_year != null ?
                new ObjectParameter("publish_year", publish_year) :
                new ObjectParameter("publish_year", typeof(string));
    
            var categoryNameParameter = categoryName != null ?
                new ObjectParameter("categoryName", categoryName) :
                new ObjectParameter("categoryName", typeof(string));
    
            var languageNameParameter = languageName != null ?
                new ObjectParameter("languageName", languageName) :
                new ObjectParameter("languageName", typeof(string));
    
            var roleNameParameter = roleName != null ?
                new ObjectParameter("roleName", roleName) :
                new ObjectParameter("roleName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_search_books_Result>("sp_search_books", titleParameter, authorParameter, publish_yearParameter, categoryNameParameter, languageNameParameter, roleNameParameter);
        }
    
        public virtual ObjectResult<sp_reservation_save_Result> sp_reservation_save(Nullable<System.DateTime> date_reserved_from, Nullable<System.DateTime> date_reserved_to, string user_membership_id, Nullable<int> book_isbn)
        {
            var date_reserved_fromParameter = date_reserved_from.HasValue ?
                new ObjectParameter("date_reserved_from", date_reserved_from) :
                new ObjectParameter("date_reserved_from", typeof(System.DateTime));
    
            var date_reserved_toParameter = date_reserved_to.HasValue ?
                new ObjectParameter("date_reserved_to", date_reserved_to) :
                new ObjectParameter("date_reserved_to", typeof(System.DateTime));
    
            var user_membership_idParameter = user_membership_id != null ?
                new ObjectParameter("user_membership_id", user_membership_id) :
                new ObjectParameter("user_membership_id", typeof(string));
    
            var book_isbnParameter = book_isbn.HasValue ?
                new ObjectParameter("book_isbn", book_isbn) :
                new ObjectParameter("book_isbn", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_reservation_save_Result>("sp_reservation_save", date_reserved_fromParameter, date_reserved_toParameter, user_membership_idParameter, book_isbnParameter);
        }
    }
}
